CREATE TABLE Tag(
	tagID INTEGER PRIMARY KEY,
	tagName TEXT NOT NULL
);

CREATE TABLE EntriesTags(
	tagID INTEGER NOT NULL REFERENCES Tag(tagID) ON DELETE CASCADE,
	entryID INTEGER NOT NULL REFERENCES Entry(entryID) ON DELETE CASCADE,
	PRIMARY KEY (tagID, entryID)
);
