CREATE TABLE Tag(
	tagID INTEGER PRIMARY KEY,
	tagName TEXT NOT NULL
);

CREATE TABLE EntriesTags(
	tagID INTEGER REFERENCES Tag(tagID) NOT NULL,
	entryID INTEGER REFERENCES Entry(entryID) NOT NULL,
	PRIMARY KEY (tagID, entryID)
);
