module Domain where

-- -- * Creating
--
-- createEntry :: String -> String -> IO Entry
-- createEntry name desc = undefined
--
-- createTag :: String -> IO Tag
-- createTag name = undefined
--
-- createUser :: String -> IO User
-- createUser name = undefined
--
-- createCol :: String -> Board -> IO Column
-- createCol name board = undefined
--
-- createBoard :: String -> String -> IO Board
-- createBoard name desc = undefined
--
-- -- * Entry actions
--
-- renameEntry :: Entry -> String -> String -> Entry
-- renameEntry entry newName "" = undefined
-- renameEntry entry newName newDesc = undefined
--
-- assign :: Entry -> User -> Entry
-- assign entry assignee = undefined
--
-- unassign :: Entry -> Entry
-- unassign entry = undefined
--
-- moveEntry :: Entry -> Column -> Entry
-- moveEntry entry to = undefined
--
-- removeEntry :: Entry -> Entry
-- removeEntry entry = undefined
--
-- -- * Tag actions
--
-- addTag :: Tag -> Entry -> Entry
-- addTag tag entry = undefined
--
-- renameTag :: Tag -> String -> Tag
-- renameTag tag newName = undefined
--
-- removeTag :: Tag -> Entry -> Entry
-- removeTag tag entry = undefined
--
-- -- * Users actions
--
-- renameUser :: User -> String -> User
-- renameUser user newName = undefined
--
-- -- * Column actions
--
-- renameColumn :: Column -> String -> Column
-- renameColumn col newName = undefined
--
-- -- * Board actions
--
-- setDefaultCol :: Board -> Column -> Board
-- setDefaultCol board col = undefined
--
-- addUser :: Board -> User -> Board
-- addUser board user = undefined
--
-- removeUser :: Board -> User -> Board
-- removeUser board user = undefined
--
-- reorderColumns :: Board -> Int -> Int -> Board
-- reorderColumns board i j = undefined
--
